In [6]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [14]:
df = pd.read_csv(r"D:\Machine Learning 100 days\Day_29_ML_Pipelines\train.csv")

In [16]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [22]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [24]:
#step 1 ->train/test/split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'])

In [28]:
X_train.head(2)

Pclass   Sex   Age  SibSp  Parch   Fare Embarked
382       3  male  32.0      0      0  7.925        S
784       3  male  25.0      0      0  7.050        S

In [30]:
Y_train.head()

382    0
784    0
706    1
32     1
754    1
Name: Survived, dtype: int64

In [32]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [34]:
#applying imputation on age and embarked because they have missing values
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [36]:
X_train_age

array([[32.        ],
       [25.        ],
       [45.        ],
       [29.57222222],
       [48.        ],
       [34.        ],
       [25.        ],
       [35.        ],
       [42.        ],
       [40.        ],
       [26.        ],
       [18.        ],
       [29.57222222],
       [45.        ],
       [ 5.        ],
       [29.57222222],
       [27.        ],
       [28.        ],
       [28.        ],
       [27.        ],
       [29.57222222],
       [36.        ],
       [36.        ],
       [25.        ],
       [22.        ],
       [17.        ],
       [36.        ],
       [19.        ],
       [42.        ],
       [29.57222222],
       [26.        ],
       [60.        ],
       [29.57222222],
       [28.        ],
       [23.        ],
       [18.        ],
       [36.        ],
       [48.        ],
       [29.57222222],
       [37.        ],
       [29.57222222],
       [29.57222222],
       [26.        ],
       [40.        ],
       [29.57222222],
       [20

In [38]:
X_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
      

In [42]:
# one hot encoding in sex and Embarked(categorail data)
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [44]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], shape=(668, 2))

In [46]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], shape=(668, 3))

In [50]:
X_train.head(2)

Pclass   Sex   Age  SibSp  Parch   Fare Embarked
382       3  male  32.0      0      0  7.925        S
784       3  male  25.0      0      0  7.050        S

In [52]:
#now we have different array of sex,age and embarled so we need to add all the array together now

In [54]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [56]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [58]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [60]:
X_train_transformed #we have combined all the columns

array([[3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [3., 4., 1., ..., 0., 1., 0.],
       [3., 0., 0., ..., 0., 0., 1.]], shape=(668, 10))

In [62]:
X_test_transformed

array([[1., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [3., 5., 2., ..., 0., 0., 1.],
       ...,
       [3., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(223, 10))

In [66]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,Y_train)

DecisionTreeClassifier()

In [68]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.7892376681614349

In [76]:
import pickle

In [80]:
pickle.dump(ohe_sex,open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/clf.pkl','wb'))