In [96]:
import pickle
import numpy as np
import pandas as pd

In [98]:
ohe_sex = pickle.load(open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/ohe_embarked.pkl','rb'))
clf = pickle.load(open('D:/Machine Learning 100 days/Day_29_ML_Pipelines/clf.pkl','rb'))

#we are getting these model which saved  in last file

In [100]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked

# Column names (based on training data)
columns = ['Pclass', 'Sex', 'age', 'SibSp', 'Parch', 'Fare', 'Embarked']

# User input as a NumPy array
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1, 7)

# Convert to a DataFrame
test_input_df = pd.DataFrame(test_input, columns=columns)


In [102]:
test_input_df

Pclass   Sex   age SibSp Parch  Fare Embarked
0      2  male  31.0     0     0  10.5        S

In [109]:
# Access the 'gender' column by its name
test_input_sex = ohe_sex.transform(test_input_df[['Sex']])

# Print the transformed gender data
print(test_input_sex)


[[0. 1.]]


In [111]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [113]:
test_input_embarked

array([[0., 0., 1.]])

In [115]:
test_input_age = test_input[:,2].reshape(1,1)

In [117]:
test_input_age

array([[31.0]], dtype=object)

In [119]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [121]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [123]:
test_input_transformed.shape

(1, 10)

In [125]:
clf.predict(test_input_transformed)


array([0])