In [21]:
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv(r"D:\Machine Learning 100 days\Day_26_ordinal_encoding\customer.csv")

In [25]:
df.sample(5)

age  gender review education purchased
1    68  Female   Poor        UG        No
2    70  Female   Good        PG        No
14   15    Male   Poor        PG       Yes
31   22  Female   Poor    School       Yes
16   59    Male   Poor        UG       Yes

In [27]:
#age is numerical
#gender is nomial so we need to apply one hot encoding which we did not study yet
#review and education are ordinal so we will apply 
#perchased is in target so we need to apply label encoding on that
#so we will remove age and gender as of now....



df = df.iloc[:,2:]

In [29]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2) #in x first two cols and in y last col

In [39]:
X_train.head()

review education
45     Poor        PG
14     Poor        PG
26     Poor        PG
25     Good    School
0   Average    School

In [41]:
X_test.head()

review education
34  Average    School
33     Good        PG
2      Good        PG
28     Poor    School
3      Good        PG

In [43]:
Y_train.head()

45    Yes
14    Yes
26     No
25     No
0      No
Name: purchased, dtype: object

In [45]:
Y_test.head()

34     No
33    Yes
2      No
28     No
3      No
Name: purchased, dtype: object

In [47]:
from sklearn.preprocessing import OrdinalEncoder

In [49]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) #we have given in increasing order

In [53]:
oe.fit(X_train)  #train ke upar fit karte hai but train and test dono ke upar transform karte hai

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [55]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [57]:
X_train

array([[0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [0., 0.]])

In [61]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [63]:
#now doing label encoding on output column
from sklearn.preprocessing import LabelEncoder

In [69]:
le = LabelEncoder()  #here no need to define order only two values are there

In [71]:
le.fit(Y_train)

LabelEncoder()

In [73]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [75]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [79]:
Y_train

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [81]:
Y_test

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0])